[algokit]
min_version = "v2.0.0"

[project]
type = "contract"
name = "climate-dao"
artifacts = "contracts/artifacts"

[project.deploy]
command = "poetry run python -m contracts deploy"

[project.deploy.localnet]

[project.run.build]
description = "Build smart contracts"
commands = [
  "poetry run python -m contracts build"
]
